# Generated by Django 5.2.10 on 2026-02-11 06:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiningPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True, max_length=500)),
                ('meta_keywords', models.CharField(blank=True, max_length=300)),
                ('hero_title', models.CharField(default='Dining Experience', max_length=200)),
                ('hero_subtitle', models.TextField(default='Farm-to-fork dining in a serene, non-alcoholic environment')),
                ('intro_text', models.TextField(default='Experience fresh, organic meals prepared with ingredients from our own farm. Enjoy dining in our beautiful pergolas and gazebos surrounded by nature.')),
                ('farm_title', models.CharField(default='Farm-to-Fork Freshness', max_length=200)),
                ('farm_subtitle', models.TextField(default='All ingredients sourced directly from our organic farm')),
                ('spaces_title', models.CharField(default='Prime Dining Spaces', max_length=200)),
                ('spaces_subtitle', models.TextField(default='Beautiful locations for memorable dining experiences')),
                ('menu_pdf', models.FileField(blank=True, help_text='Upload PDF menu file', upload_to='dining/menus/')),
                ('menu_title', models.CharField(default='Our Menu', max_length=200)),
                ('menu_subtitle', models.TextField(default='Fresh, organic, and delicious')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Dining Page Settings',
                'verbose_name_plural': 'Dining Page Settings',
            },
        ),
        migrations.CreateModel(
            name='DiningSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('space_type', models.CharField(choices=[('pergola', 'Pergola'), ('gazebo', 'Gazebo'), ('garden', 'Garden Dining')], max_length=20)),
                ('description', models.TextField()),
                ('capacity', models.IntegerField(help_text='Number of people', validators=[django.core.validators.MinValueValidator(1)])),
                ('ideal_for', models.TextField(help_text='Ideal occasions, one per line')),
                ('has_lighting', models.BooleanField(default=True)),
                ('has_power', models.BooleanField(default=True)),
                ('is_covered', models.BooleanField(default=True)),
                ('is_private', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Dining Space',
                'verbose_name_plural': 'Dining Spaces',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='FarmSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('source_type', models.CharField(choices=[('vegetable', 'Vegetables'), ('fruit', 'Fruits'), ('herb', 'Herbs'), ('meat', 'Meat'), ('dairy', 'Dairy')], max_length=20)),
                ('icon', models.CharField(help_text='Font Awesome icon class', max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='dining/farm/')),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Farm Source',
                'verbose_name_plural': 'Farm Sources',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('category_type', models.CharField(choices=[('juices', 'Fresh Juices'), ('mocktails', 'Mocktails & Coffee'), ('platters', 'Platters'), ('mains', 'Main Dishes'), ('bbq', 'BBQ / Choma Zone'), ('desserts', 'Desserts')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(help_text='Font Awesome icon class', max_length=50)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Food Category',
                'verbose_name_plural': 'Food Categories',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True, max_length=500)),
                ('meta_keywords', models.CharField(blank=True, max_length=300)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(help_text='Brief description of the dish')),
                ('is_from_farm', models.BooleanField(default=False)),
                ('farm_ingredients', models.TextField(blank=True, help_text='List farm-sourced ingredients, one per line')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Optional - price can be shown subtly or not at all', max_digits=10, null=True)),
                ('featured_image', models.ImageField(help_text='High-quality food photo', upload_to='dining/food/')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_special', models.BooleanField(default=False, help_text="Chef's special")),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to='dining.foodcategory')),
            ],
            options={
                'verbose_name': 'Food Item',
                'verbose_name_plural': 'Food Items',
                'ordering': ['category', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='SpaceGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='dining/spaces/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('display_order', models.IntegerField(default=0)),
                ('dining_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='dining.diningspace')),
            ],
            options={
                'verbose_name': 'Space Gallery Image',
                'verbose_name_plural': 'Space Gallery Images',
                'ordering': ['display_order'],
            },
        ),
    ]
