# Generated by Django 5.2.10 on 2026-02-11 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dining', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='High-quality food photo', upload_to='dining/food/'),
        ),
    ]
