# Generated by Django 5.2.10 on 2026-01-16 13:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('category_type', models.CharField(choices=[('board', 'Board Rooms'), ('meeting', 'Meeting Rooms'), ('hall', 'Meeting Hall'), ('training', 'Training & Workshops')], max_length=20)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text='Font Awesome icon class', max_length=50)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Conference Category',
                'verbose_name_plural': 'Conference Categories',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='ConferencePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('includes', models.TextField(help_text='List package inclusions, one per line')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.CharField(help_text='e.g., Half Day, Full Day', max_length=100)),
                ('suitable_for', models.TextField(help_text='Ideal for which type of meetings')),
                ('is_popular', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Conference Package',
                'verbose_name_plural': 'Conference Packages',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='ConferencePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True, max_length=500)),
                ('meta_keywords', models.CharField(blank=True, max_length=300)),
                ('hero_title', models.CharField(default='Conference & Meetings', max_length=200)),
                ('hero_subtitle', models.TextField(default='State-of-the-art meeting facilities in a serene, non-alcoholic environment')),
                ('intro_text', models.TextField(default='From intimate board meetings to large conferences, we have the perfect space for your business needs.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Conference Page Settings',
                'verbose_name_plural': 'Conference Page Settings',
            },
        ),
        migrations.CreateModel(
            name='ConferenceRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True, max_length=500)),
                ('meta_keywords', models.CharField(blank=True, max_length=300)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('room_type', models.CharField(choices=[('executive', 'Executive Room'), ('standard', 'Standard Room'), ('board', 'Board Room'), ('hall', 'Conference Hall')], max_length=20)),
                ('description', models.TextField()),
                ('capacity_classroom', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('capacity_theatre', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('capacity_banquet', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('capacity_u_shape', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('capacity_boardroom', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('has_projector', models.BooleanField(default=True)),
                ('has_sound_system', models.BooleanField(default=True)),
                ('has_wifi', models.BooleanField(default=True)),
                ('has_whiteboard', models.BooleanField(default=True)),
                ('has_air_conditioning', models.BooleanField(default=True)),
                ('has_natural_light', models.BooleanField(default=True)),
                ('has_secretary_space', models.BooleanField(default=False)),
                ('has_video_conferencing', models.BooleanField(default=False)),
                ('dimensions', models.CharField(blank=True, max_length=100)),
                ('floor_area', models.CharField(blank=True, max_length=50)),
                ('half_day_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('full_day_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('featured_image', models.ImageField(blank=True, upload_to='conferences/rooms/')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='conferences.conferencecategory')),
            ],
            options={
                'verbose_name': 'Conference Room',
                'verbose_name_plural': 'Conference Rooms',
                'ordering': ['category', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RoomGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='conferences/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('display_order', models.IntegerField(default=0)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='conferences.conferenceroom')),
            ],
            options={
                'verbose_name': 'Room Gallery Image',
                'verbose_name_plural': 'Room Gallery Images',
                'ordering': ['display_order'],
            },
        ),
    ]
