# Generated by Django 5.2.10 on 2026-01-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Zamar Springs Gardens', max_length=200)),
                ('hero_subtitle', models.TextField(default='A serene, non-alcoholic garden venue')),
            ],
            options={
                'verbose_name_plural': 'Home Page Settings',
            },
        ),
    ]
