# Generated by Django 5.2.10 on 2026-01-16 12:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=50)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=50)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.AlterModelOptions(
            name='homepagesettings',
            options={'verbose_name': 'Home Page Settings', 'verbose_name_plural': 'Home Page Settings'},
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='address',
            field=models.TextField(default='Kiambu Road, 45 minutes from Nairobi CBD'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='email',
            field=models.EmailField(default='info@zamargardens.com', max_length=254),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='events_hosted',
            field=models.IntegerField(default=500, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='features_subtitle',
            field=models.TextField(blank=True, default='Discover our unique offerings that make us the perfect choice for your events'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='features_title',
            field=models.CharField(default='Why Choose Zamar Springs?', max_length=200),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='happy_customers',
            field=models.IntegerField(default=2000, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='operating_hours',
            field=models.TextField(default='Open Daily: 8:00 AM - 10:00 PM'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='phone_number',
            field=models.CharField(default='+254 700 123 456', max_length=20),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='years_experience',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='hero_subtitle',
            field=models.TextField(default='A serene, non-alcoholic garden venue for conferences, events, dining and family fun - just 45 minutes from Nairobi'),
        ),
    ]
