# Generated by Django 5.2.10 on 2026-01-27 05:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_feature_service_alter_homepagesettings_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagesettings',
            name='address',
            field=models.TextField(default='Kithini, Machakos, 45 minutes from Nairobi CBD'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='email',
            field=models.EmailField(default='info@zamarsprings.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='events_hosted',
            field=models.IntegerField(default=200, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='phone_number',
            field=models.CharField(default='0112394681', max_length=20),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='years_experience',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
