# Generated by Django 5.2.10 on 2026-01-27 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_homepagesettings_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagesettings',
            name='hero_subtitle',
            field=models.TextField(default='A serene, non-alcoholic garden venue for conferences, events, dining and family fun - located in Mua Hills, Machakos'),
        ),
    ]
