# Generated by Django 5.2.10 on 2026-02-10 07:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True, max_length=500)),
                ('meta_keywords', models.CharField(blank=True, max_length=300)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('wedding', 'Weddings'), ('private', 'Private Events'), ('general', 'General Events')], max_length=20)),
                ('icon', models.CharField(help_text='Font Awesome icon class', max_length=50)),
                ('description', models.TextField()),
                ('detailed_description', models.TextField(blank=True)),
                ('includes', models.TextField(blank=True, help_text='Services included, one per line')),
                ('starting_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Event Type',
                'verbose_name_plural': 'Event Types',
                'ordering': ['category', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='Garden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('garden_type', models.CharField(choices=[('main', 'Main Garden'), ('event', 'Event Garden'), ('special', 'Special Garden')], max_length=20)),
                ('capacity', models.IntegerField(help_text='Maximum capacity for events', validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField()),
                ('featured_image', models.ImageField(blank=True, upload_to='gardens/')),
                ('has_covered_area', models.BooleanField(default=True)),
                ('has_power', models.BooleanField(default=True)),
                ('has_lighting', models.BooleanField(default=True)),
                ('has_restrooms', models.BooleanField(default=True)),
                ('has_parking', models.BooleanField(default=True)),
                ('is_wheelchair_accessible', models.BooleanField(default=True)),
                ('area', models.CharField(blank=True, max_length=100)),
                ('special_features', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Garden',
                'verbose_name_plural': 'Gardens',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GardensPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True, max_length=500)),
                ('meta_keywords', models.CharField(blank=True, max_length=300)),
                ('hero_title', models.CharField(default='Gardens & Events', max_length=200)),
                ('hero_subtitle', models.TextField(default='Beautiful garden venues for weddings, events, and celebrations in a serene, non-alcoholic environment')),
                ('intro_text', models.TextField(default='From intimate garden weddings to large corporate events, our beautifully maintained gardens provide the perfect backdrop for your special occasions.')),
                ('is_active', models.BooleanField(default=True)),
                ('why_title', models.CharField(default='Why Choose Our Gardens', max_length=200)),
                ('why_subtitle', models.TextField(default='Experience the perfect blend of natural beauty and professional event hosting')),
            ],
            options={
                'verbose_name': 'Gardens Page Settings',
                'verbose_name_plural': 'Gardens Page Settings',
            },
        ),
        migrations.CreateModel(
            name='EventGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gardens/events/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('display_order', models.IntegerField(default=0)),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='gardens.eventtype')),
            ],
            options={
                'verbose_name': 'Event Gallery Image',
                'verbose_name_plural': 'Event Gallery Images',
                'ordering': ['display_order'],
            },
        ),
    ]
