# Generated by Django 5.2.10 on 2026-01-17 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('error', 'Error'), ('success', 'Success')], max_length=20)),
                ('module', models.CharField(choices=[('conferences', 'Conferences'), ('home', 'Home'), ('gardens', 'Gardens'), ('dining', 'Dining'), ('kids', 'Kids'), ('bookings', 'Bookings'), ('gallery', 'Gallery'), ('packages', 'Packages'), ('contact', 'Contact'), ('about', 'About'), ('system', 'System')], max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('action_url', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Admin Notification',
                'verbose_name_plural': 'Admin Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuickLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('url', models.CharField(max_length=500)),
                ('icon', models.CharField(help_text='Font Awesome icon class', max_length=50)),
                ('module', models.CharField(choices=[('conferences', 'Conferences'), ('home', 'Home'), ('gardens', 'Gardens'), ('dining', 'Dining'), ('kids', 'Kids'), ('bookings', 'Bookings'), ('gallery', 'Gallery'), ('packages', 'Packages'), ('contact', 'Contact'), ('about', 'About'), ('system', 'System')], max_length=50)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Quick Link',
                'verbose_name_plural': 'Quick Links',
                'ordering': ['module', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='AdminActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('view', 'View'), ('login', 'Login'), ('logout', 'Logout')], max_length=20)),
                ('module', models.CharField(choices=[('conferences', 'Conferences'), ('home', 'Home'), ('gardens', 'Gardens'), ('dining', 'Dining'), ('kids', 'Kids'), ('bookings', 'Bookings'), ('gallery', 'Gallery'), ('packages', 'Packages'), ('contact', 'Contact'), ('about', 'About'), ('system', 'System')], max_length=50)),
                ('description', models.TextField()),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('object_id', models.IntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Activity',
                'verbose_name_plural': 'Admin Activities',
                'ordering': ['-created_at'],
            },
        ),
    ]
