# Generated by Django 5.2.10 on 2026-02-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('weddings', 'Weddings & Special Events'), ('conferences', 'Conferences & Corporate Events'), ('dining', 'Dining & Farm-to-Fork Experience'), ('kids_family', 'Kids & Family Fun'), ('gardens', 'Gardens & Outdoor Spaces')], max_length=30)),
                ('image_path', models.CharField(help_text='Absolute static/media path, e.g. /static/images/gallery/file.webp', max_length=300)),
                ('alt_text', models.CharField(max_length=250)),
                ('caption', models.CharField(blank=True, max_length=280)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['category', 'display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='GalleryPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True, max_length=500)),
                ('meta_keywords', models.CharField(blank=True, max_length=300)),
                ('hero_title', models.CharField(default='Hotel Gallery', max_length=200)),
                ('hero_subtitle', models.TextField(default='Explore weddings, events, dining, kids activities, and outdoor spaces at Zamar Springs Gardens.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Gallery Page Settings',
                'verbose_name_plural': 'Gallery Page Settings',
            },
        ),
    ]
