# Generated by Django 5.2.10 on 2026-02-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialPost",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("platform", models.CharField(choices=[("instagram", "Instagram"), ("tiktok", "TikTok"), ("facebook", "Facebook")], max_length=20)),
                ("post_id", models.CharField(max_length=120)),
                ("caption", models.TextField(blank=True)),
                ("media_url", models.URLField(blank=True, max_length=500)),
                ("permalink", models.URLField(max_length=500)),
                ("timestamp", models.DateTimeField()),
                ("archived", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["platform", "-timestamp"],
            },
        ),
        migrations.AddConstraint(
            model_name="socialpost",
            constraint=models.UniqueConstraint(fields=("platform", "post_id"), name="unique_social_post_platform_id"),
        ),
        migrations.AddIndex(
            model_name="socialpost",
            index=models.Index(fields=["platform", "archived", "-timestamp"], name="gal_soc_p_a_ts_idx"),
        ),
        migrations.AddIndex(
            model_name="socialpost",
            index=models.Index(fields=["post_id"], name="gal_soc_post_id_idx"),
        ),
    ]
