# Generated by Django 5.2.10 on 2026-02-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_type', models.CharField(choices=[('conference_room', 'Conference Room Booking'), ('conference_package', 'Conference Package Inquiry'), ('garden_event', 'Garden Event Inquiry'), ('garden_booking', 'Garden Booking'), ('dining_reservation', 'Dining Reservation'), ('general', 'General Inquiry')], default='general', max_length=30)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('confirmed', 'Confirmed'), ('closed', 'Closed')], default='new', max_length=20)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('service_name', models.CharField(blank=True, max_length=200)),
                ('event_type', models.CharField(blank=True, max_length=120)),
                ('attendees', models.PositiveIntegerField(blank=True, null=True)),
                ('requested_date', models.DateField(blank=True, null=True)),
                ('requested_time', models.CharField(blank=True, max_length=20)),
                ('budget', models.CharField(blank=True, max_length=80)),
                ('source_page', models.CharField(blank=True, max_length=250)),
                ('message', models.TextField(blank=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
