# Generated by Django 5.2.10 on 2026-02-20 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_bookingrequest_event_window'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingrequest',
            name='request_type',
            field=models.CharField(choices=[('conference_room', 'Conference Room Booking'), ('conference_package', 'Conference Package Inquiry'), ('garden_event', 'Garden Event Inquiry'), ('garden_booking', 'Garden Booking'), ('dining_reservation', 'Dining Reservation'), ('outdoor_event', 'Outdoor Event Inquiry'), ('general', 'General Inquiry')], default='general', max_length=30),
        ),
    ]
